### PR TITLE
Update v11.0.0

### PR DESCRIPTION
**Pull request by ckoern**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ckoern** [comment]
@conda-forge-admin, please rerender

**Comment by ckoern** [comment]
Mhm, the python 3.10 build seem to fail due to a bug in boost handling double digit python minor versions. This was fixed in boost 1.77 but version 1.74 was pinned by `conda-forge-pinning`. 
@chrisburr Anything I can do about it?

Also I had to add the `-D_LIBCPP_DISABLE_AVAILABILITY` to `CXXFLAGS` for OSX targets, otherwise `std::filesystem` is not available. I hope this is fine? This was also done in conda-forge/z5py-feedstock#47

**Comment by chrisburr** [comment]
>Also I had to add the -D_LIBCPP_DISABLE_AVAILABILITY to CXXFLAGS for OSX targets, otherwise std::filesystem is not available.

Yup, that's fine: https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk

> Mhm, the python 3.10 build seem to fail due to a bug in boost handling double digit python minor versions. This was fixed in boost 1.77 but version 1.74 was pinned by conda-forge-pinning.

Ouch. Are you aware of any other packages which are affected?

Updating boost will require a migration to rebuild everything that depends on boost (I suspect a boost 1.78 migration will happen "soon" but then tend to be slow). For now there is two options:

* Come up with a hack to make the build pass (it's ugly but `sed` can work miracles 😆)
* Backport the upstream patch to conda-forge's build of boost [here](https://github.com/conda-forge/boost-feedstock/blob/v1.74.x/recipe/meta.yaml)

Any preference?

**Comment by ckoern** [comment]
Let's do it the correct way via backporting, I am surprised I couldn't find any other feedstock having the same issue!

**Comment by ckoern** [comment]
Mhm, strange that it still fails... I will have to dig a bit into it

**Comment by chrisburr** [comment]
Thanks, if you need a hand or have questions let me know :smile:

**Comment by ckoern** [comment]
Aaaaah, the BoostConfig.cmake is provided by `boost-cpp` not `boost`...

Is there any way I can run the `geant4` build locally but supply a local-built version of the `boost-cpp` package instead of using the conda-forge one?

**Comment by chrisburr** [comment]
Ah ha! I thought it was a multi-output feedstock 😅 

You should be able to use something along the lines of:
```sh
cd boost-cpp-feedstock
conda mambabuild -m ci_support/something.yaml recipe/
cd ..
cd geant4-feedstock
conda mambabuild -c local -m ci_support/something.yaml recipe/
cd ..
```

**Comment by ckoern** [comment]
@conda-forge-admin, please restart ci

**Comment by chrisburr** [comment]
Thanks @ckoern! 🍰

**Pull request merged**
