### PR TITLE
Update to 10.6.2 and simplify

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@drbenmorgan I think this includes the fixes we discussed earlier this year (I've ended up needing it for DD4hep hence the sudden push from my side). The interesting files are in here https://github.com/chrisburr/geant4-feedstock/tree/update-10.6.2/recipe with the main things being:
* [`meta.yaml`](https://github.com/chrisburr/geant4-feedstock/blob/update-10.6.2/recipe/meta.yaml): Metadata including the dependencies.
* [`build_geant4.sh`](https://github.com/chrisburr/geant4-feedstock/blob/update-10.6.2/recipe/build_geant4.sh): The build script.
* [`cmake-dont-remember-opengl-path.patch`](https://github.com/chrisburr/geant4-feedstock/blob/update-10.6.2/recipe/patches/cmake-dont-remember-opengl-path.patch): A patch to prevent Geant4 from remembering where it previously found OpenGL. I still think the CMake configuration is remembering too much but this is the most troublesome bit.

If you have any thoughts, particularly with regard to if features should be enabled/disabled let me know.

My biggest outstanding question is with regard to multithreading. There was previously [this issue](https://github.com/conda-forge/geant4-feedstock/pull/2) which caused it to be disabled. Is there a workaround to avoid it that you know of? Or is there really a need both a single-threaded and multi-threaded build?

**Comment by drbenmorgan** [comment]
Hi @chrisburr, this is great (and apologies it went on my back burner...)! All of the key options are there, the only one to maybe consider is `GEANT4_USE_SYSTEM_CLHEP=ON`, with an associated dependency on CLHEP. That might be best if applications are being built against Geant4 which also directly/indirectly depend on CLHEP to avoid symbol clashes.

> * [`cmake-dont-remember-opengl-path.patch`](https://github.com/chrisburr/geant4-feedstock/blob/update-10.6.2/recipe/patches/cmake-dont-remember-opengl-path.patch): A patch to prevent Geant4 from remembering where it previously found OpenGL. I still think the CMake configuration is remembering too much but this is the most troublesome bit.

The CMake configuration from 10.6 stores the build-time locations of dependencies in a `G4PackageCache.cmake` file that is installed by default. That can be disabled by adding `-DGEANT4_INSTALL_PACKAGE_CACHE=OFF` to the CMake flags. Use of the install through CMake `find_package(Geant4 ...)` then requires that CMake can locate the needed dependencies, e.g. they are in `CMAKE_PREFIX_PATH` or similar. If Conda sets this for an environment, it should be fine.

> My biggest outstanding question is with regard to multithreading. There was previously [this issue](https://github.com/conda-forge/geant4-feedstock/pull/2) which caused it to be disabled. Is there a workaround to avoid it that you know of? Or is there really a need both a single-threaded and multi-threaded build?

I think that issue can be resolved by always building multithreaded _and_ adding `-DGEANT4_BUILD_TLS_MODEL=global-dynamic` to the CMake flags. Geant4 uses `initial-exec` TLS by default as this gives the best performance, but is not usable in the case that the libraries are loaded dynamically. Changing to `global-dynamic` removes that issue, and the performance difference should only be 1-2%.

**Comment by chrisburr** [comment]
Thanks for getting back to me so quickly, those three suggestions all look good to me.

I've just made a PR to bump the version of CLHEP (https://github.com/conda-forge/clhep-feedstock/pull/5), once that's merged I'll apply the changes here and merge this PR.

**Comment by chrisburr** [comment]
Thanks for the help @drbenmorgan, everything seems to be working now.

One last question, is there a good way of making sure the versions of the datasets are kept in sync. At the moment I'm just copying the versions from `Geant4DatasetDefinitions.cmake`  but that seems error prone:

https://github.com/conda-forge/geant4-feedstock/blob/5d227909576961813aa90df07123835d7811985b/recipe/meta.yaml#L58-L70

I don't care about changing the versions by hand, I just want to know when I get it wrong 😆 I'm thinking some kind of `check_dataset_versions` script would be useful to run during the package build and/or tests and it would probably be useful for other package managers as well.

**Comment by drbenmorgan** [comment]
Thanks @chrisburr, it's great to have Geant4 in Conda!

Would the `check_dataset_versions` script be something that would go in this recipe, or for Geant4 itself? One issue at the moment would identifying the version as it's only really present in the directory name for the dataset at the moment. If the datasets are being installed as-is that's probably fine (I do want to add better "manifest" info for the data longterm...).

**Comment by chrisburr** [comment]
As it is generally useful for any packaging efforts I think it would be nice to have in Geant4 itself. It's not particularly important, so it probably makes sense to add whenever the "dataset manifests" are added/improved.

**Pull request merged**
