### PR TITLE
Enable qt variant

### PR DESCRIPTION
**Pull request by op3**
Enable qt variant as discussed [here](https://github.com/conda-forge/geant4-feedstock/issues/4).

### CODE REVIEW

**Comment by op3** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
Why is xquartz needed? If not really essential, I would vote against using it since it looks pretty horrible on retina screens...

**Comment by chrisburr** [comment]
GEANT4 is looking for OpenGL [here](https://github.com/Geant4/geant4/blob/master/cmake/Modules/Geant4InterfaceOptions.cmake#L256-L275) which causes the build to fail [like this](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=62595&view=logs&jobId=dd4383b7-230e-5972-2d6d-dcd64038bc3b). On my machine that's provided by xquartz[1] but I've only briefly looked for alternatives.

The I think the alternative is to set `-DGEANT4_USE_OPENGL_X11=OFF` and `-DGEANT4_USE_RAYTRACER_X11=OFF` for macOS. As I've never used the visualisation, do you know if these components are likely to be useful?

[1] Ideally we should add it to conda-forge, but using brew is a hack that will work for now. See https://github.com/conda-forge/conda-smithy/issues/1089

**Comment by chrisburr** [comment]
Okay both options appear to work the only difference I can see is that the RayTracer visualization is disabled.

@op3 and @tschoonj Any preference between reverting 3575b66 or merging this as is?

**Comment by tschoonj** [comment]
Looks good to me. OpenGL is now officially deprecated on macOS, so perhaps best not to support it.

**Comment by op3** [comment]
I don’t know about the exact features that are missing without OpenGL/X11, but apparently the Qt visualization interface is supposed to work without it. I think this is the cleaner solution, so I support removing it for MacOS builds.

**Pull request merged**
